name: Deploy React App

on:
  push:
    branches:
      - main  # Ou outra branch de deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build React App
      run: |
        npm install
        npm run build

    - name: Deploy to DigitalOcean Droplet
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Instalar Docker Compose se não estiver instalado
          if ! [ -x "$(command -v docker-compose)" ]; then
            curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
          fi

          # Criar ou atualizar o diretório no servidor
          mkdir -p /var/www/react-app
          
          # Parar e remover containers antigos, se existirem
          docker-compose -f /var/www/react-app/docker-compose.yml down || true

          # Subir os novos arquivos para o servidor
          rm -rf /var/www/react-app/*
          scp -r build/* root@${{ secrets.DROPLET_IP }}:/var/www/react-app/

          # Construir e iniciar os containers
          cd /var/www/react-app
          docker-compose up -d --build
