name: Deploy React App with Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t leolsalvador1/alivelife:latest .
        docker push leolsalvador1/alivelife:latest

    - name: Deploy to DigitalOcean Droplet
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          docker pull leolsalvador1/alivelife:latest
          docker stop react-app || true
          docker rm react-app || true
          docker run -d -p 80:80 --name react-app leolsalvador1/alivelife:latest